### ISSUE TITLE
--fill-gaps eventually adds a furin cleavage site to everyone

### ISSUE THREAD

**Issue by babarlelephant** [nextstrain/avian-flu#6] opened 2021-02-21 09:32 UTC
Hi, in augur align you are calling --fill-gaps which is just doing 

```
 _seq = _seq.replace('-', 'N')
```

so that in the nextstrain tree everyone [gets a FCS](https://nextstrain.org/flu/avian/h5nx/ha?c=gt-HA_341,342,343,344,345&m=div).

I don't have access to filtered_H5Nx_HA.fasta and metadata-with-clade_H5Nx_HA.tsv so I can't make a proposal of modification of the Snakemake with a python script in order to leave the FCS indels but if I did I would be happy to make some tries. 

The only experiment I did was to download a few thousands of H5Nx sequences from genbank, to label with LPAI those with a deletion at the FCS, then to remove from the alignment the FCS region, to run mega, and I got that the LPAI sequences where [quite clustered together](http://babarlelephant.free-hoster.net/tree/H5N8_no_FCS_ha.html).

**Comment by jameshadfield** [comment] 2021-02-22 01:02
I think this is due to the default behavior of `augur translate` being to infer ambiguous nucleotides, and could be remedied by adding `--keep-ambiguous` to the [ancestral rule](https://github.com/nextstrain/avian-flu/blob/master/Snakefile#L213-L229).

**Comment by lmoncla** [comment] 2021-11-23 21:55
Thanks for flagging this! This is definitely an error caused by the combination of `--fill-gaps` in `augur align` and not having `--keep-ambiguous` in `augur translate`. This has been fixed with [this commit](https://github.com/nextstrain/avian-flu/commit/6426ccada83b89d7f8a1b653ff7f0237fb083cb7), which does a few things: 

1. Removes `--fill-gaps` in `augur align`
2. Adds `--keep-ambiguous` in `augur translate` 
3. Adds a new rule, `rule cleavage-site`, which reads in the HA alignment, translates it, and infers whether the 4 amino acids immediately preceding HA2 encode a furin cleavage motif. Here, I've defined a furin cleavage motif as the sequence `R-X-K/R-R`, where `X` is any amino acid. This results in 2 new colorby options: `furin cleavage motif`, which can be `present` or `absent`, and `cleavage site sequence`, which displays the sequence of the 4 amino acids immediately preceding HA2. 

As expected, we now display that some [high-path H5N1](https://nextstrain.org/flu/avian/h5n1/ha?c=furin_cleavage_motif&p=full) and [H5Nx](https://nextstrain.org/flu/avian/h5nx/ha?c=furin_cleavage_motif&p=full) lineages have furin cleavage sites, but that the vast majority of [H9N2](https://nextstrain.org/flu/avian/h9n2/ha?c=furin_cleavage_motif&p=full) and [H7N9](https://nextstrain.org/flu/avian/h7n9/ha?c=furin_cleavage_motif&p=full) sequences do not.

**Closed as completed** 2021-11-23 21:55 UTC
Labels: enhancement
